steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/your-project-id/flask-app-image:$COMMIT_SHA'
  - '.'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'k8s/deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-cluster-name'
images:
  - 'gcr.io/your-project-id/flask-app-image:$COMMIT_SHA'
substitutions:
  _CLUSTER_NAME: gke_vast-service-390209_us-central1_staging
