steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/vast-service-390209/flask-app-image:$COMMIT_SHA=$(git rev-parse --short HEAD)'
  - '.'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'k8s/deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke_vast-service-390209_us-central1_staging'
images:
  - 'gcr.io/your-project-id/flask-app-image:$COMMIT_SHA'
substitutions:
  _CLUSTER_NAME: staging
  

logsBucket: 'gs://logs-fadsladasasdsk-asadspp-budasdsckedst'
